# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKnYl-PbnOFth9MsbSrBCJev8P_872M2
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score

import joblib

df = pd.read_csv("olist_order_reviews_dataset.csv")

df.head()

df = df[["review_score", "review_comment_message"]]

df.rename(columns={
    "review_comment_message": "text"
}, inplace=True)

df = df.dropna(subset=["text"])

def label_sentiment(score):
    if score >= 4:
        return "Positivo"
    elif score <= 2:
        return "Negativo"
    else:
        return None  # nota 3 será descartada

df["sentiment"] = df["review_score"].apply(label_sentiment)
df = df.dropna(subset=["sentiment"])

df["sentiment"].value_counts()

df.sample(5)

X = df["text"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=5000,
        ngram_range=(1,2)
    )),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

joblib.dump(pipeline, "sentiment_model_olist.joblib")

pipeline.predict(["Entrega rápida e produto excelente"])

pipeline.predict(["Produto veio com defeito, não recomendo"])

pipeline.predict_proba(["Entrega rápida e produto excelente"])

from google.colab import files
files.download("sentiment_model_olist.joblib")

!pip install fastapi uvicorn nest-asyncio

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import joblib
import numpy as np

model = joblib.load("sentiment_model_olist.joblib")

app = FastAPI(
    title="Sentiment Analysis API",
    description="API para classificação de sentimento de avaliações de clientes",
    version="1.0"
)

class TextInput(BaseModel):
    text: str

@app.post("/predict")
def predict_sentiment(input: TextInput):

    if not input.text or len(input.text.strip()) < 5:
        raise HTTPException(
            status_code=400,
            detail="O texto deve conter pelo menos 5 caracteres."
        )

    prediction = model.predict([input.text])[0]
    probabilities = model.predict_proba([input.text])[0]

    probability = float(np.max(probabilities))

    return {
        "previsao": prediction,
        "probabilidade": round(probability, 4)
    }

class FakeInput:
    def __init__(self, text):
        self.text = text

teste = FakeInput("Entrega rápida e produto excelente")

predict_sentiment(teste)